name: ProjLab
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.17
  - pip=25.1
  - python=3.11.13
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - cryptography==45.0.5
      - dotenv==0.9.9
      - idna==3.10
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - prompt-toolkit==3.0.51
      - pycparser==2.22
      - pygithub==2.7.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynacl==1.5.0
      - python-dotenv==1.1.1
      - questionary==2.1.0
      - requests==2.32.4
      - rich==14.1.0
      - typing-extensions==4.14.1
      - urllib3==2.5.0
      - wcwidth==0.2.13
